version: '2'
services:
    p4oauth2-app:
        image: p4oauth2
        external_links:
            - p4oauth2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/p4oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    p4oauth2-mysql:
        extends:
            file: mysql.yml
            service: p4oauth2-mysql
